BEGIN 
  
SELECT MIN(BDCO_DH_LANCTO)
INTO   W_DATA_LANC_MENOR
FROM   CONSIGNACAO_SBD
WHERE  BDPR_CD_DINAP
AND    BDED_NU_EDICAO = L.BDPR_CD_DINAP
AND    BDCO_CD_RELATORIO IN ('PSE78' , 'PSE81');
IF W_DATA_LANC_MENOR >= TO_DATE ('01/09/2017' , 'DD/MM/YYYY') THEN
    W_ERP_SEGMENT6 := '038';
ELSE
    W_ERP_SEGMENT6 := '023';
END IF;
EXCEPTION WHEN NO_DATA_FOUND THEN
  W_ERP_SEGMENT6 := '038';
END;

ELSE
    IF L.BDAC_DH_LANCTO >= TO_DATE ('01/09/2017' , 'DD/MM/YYYY') THEN
       W_ERP_SEGMENT6 := '038';
    ELSE
      W_ERP_SEGMENT6 := '023';
     END IF;
 END IF;                 
